---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: agw-manual
  namespace: consul-sm
spec:
  gatewayClassName: consul
  listeners:
  - protocol: HTTP # options: HTTP or HTTPS
    port: 80 # options: 80 or 443 or custom
    name: http
    allowedRoutes:
      namespaces:
        from: All # options: All or Same or <Specific>
    # tls:
    #   certificateRefs:
    #     - name: cert
    #       namespace: secret-namespace
    #       group: ""
    #       kind: Secret
---
## ReferenceGrants enable the Consul API Gateway to route traffic between different namespaces.
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant
metadata:
  name: consul-reference-grant
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: consul-sm
  to:
    - group: ""
      kind: Service
---
## RBACs enable the Consul API gateway to interact with Consul datacenter resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-auth-binding
  namespace: consul-sm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-api-gateway-auth
subjects:
  - kind: ServiceAccount
    name: consul-server
    namespace: consul-sm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-api-gateway-tokenreview-binding
  namespace: consul-sm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: consul-api-gateway
    namespace: consul-sm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-api-gateway-auth
  namespace: consul-sm
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-api-gateway-auth-binding
  namespace: consul-sm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-api-gateway-auth
subjects:
  - kind: ServiceAccount
    name: consul-api-gateway
    namespace: consul-sm
