# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dc1
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32339       #Node port for api gateway service
        hostPort: 32339
        protocol: TCP

