apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
    consul:53 {
        errors
        cache 30
        forward . <ip-of-consul-dns-proxy-service>
        reload
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-24T05:21:56Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "3168"
  uid: efc0470c-7c5e-4fe7-bc5b-acb5f18b1616
