apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
    - name: "*"
      namespace: "*"
      consumers:
        - peer: cluster-01
        - peer: cluster-02
