apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Service
metadata:
  name: static-server
spec:
  selector:
    app: static-server
  ports:
    - port: 1234
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-server
  name: static-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
      labels:
        app: static-server
    spec:
      serviceAccountName: static-server
      containers:
      - name: static-server
        image: hashicorp/http-echo:latest
        args:
        - -listen=:8080
        - |
          -text=Application: static-server
          Cluster: KIND_CLUSTER
          Namespace: K8S_NAMESPACE
          Datacenter: DATACENTER
        ports:
        - containerPort: 8080
          name: http
