kind: ServiceIntentions
metadata:
  name: allow-cross-partition
  namespace: default
spec:
  destination:
    name: static-server
  sources:
    - name: static-client
      partition: default # Specifying where the source is coming from
      namespace: default
      action: allow
