apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: nginx
spec:
  protocol: "http"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    consul.hashicorp.com/connect-inject: "true"  # Optional: for Consul Connect sidecar injection
spec:
  serviceAccountName: nginx  # Optional: if you're using Consul ACLs or mTLS
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
