apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: static-server-intentions
spec:
  destination:
    name: static-server
  sources:
    - name: static-client
      peer: cluster-01
      action: allow
